# Generated by Django 3.0.2 on 2020-01-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DataDonation',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('donor_id', models.CharField(db_index=True, max_length=100)),
                ('ig_posts_seen', models.IntegerField()),
            ],
        ),
    ]
