# Generated by Django 3.0.2 on 2020-01-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0002_auto_20200117_1417'),
        ('data_donors', '0002_encounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='ig_item',
        ),
        migrations.AddField(
            model_name='encounter',
            name='ig_post',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='ig_observer.IgPost',
                verbose_name='Instagram Post'),
            preserve_default=False,
        ),
    ]
