# Generated by Django 3.0.2 on 2020-01-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_donors', '0003_auto_20200117_1417'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.UniqueConstraint(fields=('ig_post',
                                                       'data_donation'),
                                               name='unique_post_by_donation'),
        ),
    ]
