# Generated by Django 3.0.2 on 2020-01-21 13:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_donors', '0005_datadonationerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadonationerror',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 null=True),
        ),
    ]
