# Generated by Django 3.0.2 on 2020-01-24 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_donors', '0007_auto_20200124_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='last_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='last_status_changed',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
