# Generated by Django 3.0.2 on 2020-01-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_donors', '0009_donor_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
