# Generated by Django 3.0.2 on 2020-02-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_donors', '0010_donor_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorFollowing',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('following_ig_username', models.CharField(max_length=50)),
                ('donor',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='data_donors.Donor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='donorfollowing',
            constraint=models.UniqueConstraint(
                fields=('donor', 'following_ig_username'),
                name='unique_donor_following'),
        ),
    ]
