# Generated by Django 3.0.2 on 2020-02-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_donors', '0011_auto_20200204_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donorfollowing',
            options={
                'verbose_name': 'Donor is following',
                'verbose_name_plural': 'Donor is following'
            },
        ),
    ]
