# Generated by Django 3.0.2 on 2020-02-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_donors', '0012_auto_20200204_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadonationerror',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
