# Generated by Django 3.0.6 on 2020-05-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_donors', '0015_donor_browser'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='comments_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='likes_count',
            field=models.IntegerField(null=True),
        ),
    ]
