# Generated by Django 3.0.7 on 2020-06-24 10:16

import hashlib
import base64
from django.db import migrations, models
from django.conf import settings


def get_anonymous_id_from_username(username):
    return base64.urlsafe_b64encode(
        hashlib.pbkdf2_hmac('md5', username.encode(),
                            settings.IG_USERNAME_SALT_SECRET_KEY.encode(),
                            100000).hex().encode()).decode()


def forward(app, schema_editor):
    DonorFollowing = app.get_model('data_donors', 'DonorFollowing')
    for following in DonorFollowing.objects.all():
        new_name = get_anonymous_id_from_username(
            following.following_ig_username)
        following.following_ig_username = new_name
        following.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data_donors', '0016_auto_20200518_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorfollowing',
            name='following_ig_username',
            field=models.CharField(max_length=200),
        ),
        migrations.RunPython(forward),
    ]
