# Generated by Django 3.0.11 on 2021-04-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_donors', '0018_auto_20210413_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadonationerror',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
