export const MESSAGE_IS_LOGGED = 'MESSAGE_IS_LOGGED'
export const MESSAGE_ASK_FOR_LOGIN_CHECK = 'ASK_LOGGIN_CHECK'
export const MESSAGE_UPDATED_STATE = 'UPDATED_STATE'
export const MESSAGE_COLLECTED_DATA = 'MESSAGE_COLLECTED_DATA'
export const MESSAGE_AGREE_TO_RUN = 'MESSAGE_AGREE_TO_RUN'
export const MESSAGE_FETCH_STORE = 'MESSAGE_FETCH_STORE'
export const MESSAGE_DISPATCH = 'MESSAGE_DISPATCH'

export const LOCAL_STATE_SET_PROJECT_STATUS = 'LOCAL_STATE_SET_PROJECT_STATUS'
export const LOCAL_STATE_SET_LOGGED_IN = 'LOCAL_STATE_SET_LOGGED_IN'
export const LOCAL_STATE_SET_ALLOW_TO_RUN = 'LOCAL_STATE_SET_ALLOW_TO_RUN'
export const LOCAL_STATE_UPDATE_FOLLOWING = 'LOCAL_STATE_UPDATE_FOLLOWING'
export const LOCAL_STATE_SET_PROJECT = 'LOCAL_STATE_SET_PROJECT'
export const LOCAL_STATE_CANCEL_CHECK_LOGIN_AND_FOLLOWING =
  'LOCAL_STATE_CANCEL_CHECK_LOGIN_AND_FOLLOWING'
export const LOCAL_STATE_START_CHECK_LOGIN_AND_FOLLOWING =
  'LOCAL_STATE_START_CHECK_LOGIN_AND_FOLLOWING'
export const LOCAL_STATE_SET_FOLLOWING_ACCOUNTS =
  'LOCAL_STATE_SET_FOLLOWING_ACCOUNTS'

export const INSTAGRAM_LOGIN_URL = 'https://www.instagram.com/accounts/login/'

export const LOCAL_STORAGE_AGREE_TO_START =
  'undressing-ig//LOCAL_STORAGE_AGREE_TO_START'

export const INSTAGRAM_URL = 'https://www.instagram.com/'

export const IMPLANTED_SCRIPT_RESULT_MESSAGE =
  '__MIG_IMPLANTED_SCRIPT_RESULT_MESSAGE'
export const INJECT_SCRIPT_END_MESSAGE = '__MIG_INJECT_SCRIPT_END_MESSAGE'
