# Generated by Django 3.0.2 on 2020-01-16 16:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='IgUser',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ig_username',
                 models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='IgPost',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ig_id', models.CharField(max_length=50)),
                ('ig_shortcode', models.CharField(max_length=25)),
                ('ig_taken_at_timestamp', models.DateTimeField()),
                ('ig_type',
                 models.CharField(choices=[('GraphImage', 'GraphImage')],
                                  max_length=15)),
                ('data_json',
                 django.contrib.postgres.fields.jsonb.JSONField()),
                ('ig_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='ig_observer.IgUser')),
            ],
            options={
                'verbose_name': 'Post',
            },
        ),
    ]
