# Generated by Django 3.0.2 on 2020-01-17 14:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igpost',
            name='data_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 null=True),
        ),
        migrations.AlterField(
            model_name='igpost',
            name='ig_type',
            field=models.CharField(choices=[('GraphImage', 'GraphImage'),
                                            ('GraphSidecar', 'GraphSidecar')],
                                   max_length=15),
        ),
    ]
