# Generated by Django 3.0.2 on 2020-01-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0005_auto_20200121_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iguser',
            options={'verbose_name': 'Monitored User'},
        ),
        migrations.AddField(
            model_name='iguser',
            name='ig_biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iguser',
            name='ig_business_category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iguser',
            name='ig_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iguser',
            name='ig_id',
            field=models.CharField(blank=True,
                                   db_index=True,
                                   max_length=50,
                                   null=True,
                                   unique=True),
        ),
        migrations.AddField(
            model_name='iguser',
            name='ig_is_business_account',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iguser',
            name='ig_profile_pic',
            field=models.FileField(blank=True,
                                   null=True,
                                   upload_to='profile_pic/'),
        ),
    ]
