# Generated by Django 3.0.2 on 2020-01-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0006_auto_20200130_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='iguser',
            name='sex',
            field=models.CharField(blank=True,
                                   choices=[('F', 'Female'), ('M', 'Male')],
                                   max_length=1,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='iguser',
            name='ig_profile_pic',
            field=models.ImageField(blank=True,
                                    null=True,
                                    upload_to='profile_pic/'),
        ),
    ]
