# Generated by Django 3.0.2 on 2020-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0007_auto_20200130_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpost',
            name='created_by_donor',
            field=models.BooleanField(default=False),
        ),
    ]
