# Generated by Django 3.0.2 on 2020-01-31 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0008_igpost_created_by_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgImage',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('image_url', models.URLField()),
                ('ig_post',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='ig_observer.IgPost')),
            ],
        ),
    ]
