# Generated by Django 3.0.2 on 2020-01-31 15:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0009_igimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igimage',
            options={'verbose_name': 'Image'},
        ),
        migrations.AlterField(
            model_name='igimage',
            name='image_url',
            field=models.URLField(max_length=300),
        ),
        migrations.CreateModel(
            name='GVisionAnalyse',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('analyse', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ig_image',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='ig_observer.IgImage')),
            ],
        ),
    ]
