# Generated by Django 3.0.2 on 2020-01-31 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0011_remove_igpost_data_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvisionanalyse',
            name='created',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
