# Generated by Django 3.0.6 on 2020-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0012_gvisionanalyse_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igpost',
            name='ig_shortcode',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
