# Generated by Django 3.0.5 on 2020-04-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0012_gvisionanalyse_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='iguser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
