# Generated by Django 3.0.5 on 2020-05-06 20:08

from django.db import migrations, models


def create_a_project(app, schema_editor):
    project_model = app.get_model('ig_observer', 'Project')
    project_model.objects.create(name='Undressing IG')


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0013_iguser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name',
                 models.CharField(max_length=255,
                                  verbose_name='Project name')),
            ],
        ),
        migrations.RunPython(create_a_project, migrations.RunPython.noop)
    ]
