# Generated by Django 3.0.5 on 2020-05-06 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0014_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='iguser',
            name='project',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='ig_observer.Project'),
            preserve_default=False,
        ),
    ]
