# Generated by Django 3.0.5 on 2020-05-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0015_iguser_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True,
                                   null=True,
                                   verbose_name='Project description'),
        ),
    ]
