# Generated by Django 3.0.6 on 2020-05-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0017_auto_20200510_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_for_locale',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
