# Generated by Django 3.0.6 on 2020-05-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0018_project_default_for_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True,
                                   null=True,
                                   verbose_name='Project description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_nl',
            field=models.TextField(blank=True,
                                   null=True,
                                   verbose_name='Project description'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=255,
                                   null=True,
                                   verbose_name='Project name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_nl',
            field=models.CharField(max_length=255,
                                   null=True,
                                   verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='default_for_locale',
            field=models.CharField(
                blank=True,
                help_text=
                'A list of languages tag such as "en-US" or "fr", coma separated',
                max_length=5,
                null=True),
        ),
    ]
