# Generated by Django 3.0.6 on 2020-05-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0019_auto_20200511_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True,
                                   verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True,
                                   verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_nl',
            field=models.TextField(null=True,
                                   verbose_name='Project description'),
        ),
    ]
