# Generated by Django 3.0.6 on 2020-05-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0013_auto_20200514_1250'),
        ('ig_observer', '0020_auto_20200514_1446'),
    ]

    operations = []
