# Generated by Django 3.0.6 on 2020-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0021_merge_20200514_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpost',
            name='ig_media_caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
