# Generated by Django 3.0.7 on 2020-07-22 16:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0023_auto_20200624_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgEngagements',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments_count', models.IntegerField(null=True)),
                ('comments',
                 django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                null=True)),
                ('likes_count', models.IntegerField(null=True)),
                ('ig_post',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='ig_observer.IgPost')),
            ],
        ),
    ]
