# Generated by Django 3.0.7 on 2020-07-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0024_igengagements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igengagements',
            options={
                'verbose_name': 'Engagements',
                'verbose_name_plural': 'Engagements'
            },
        ),
    ]
