# Generated by Django 3.0.7 on 2020-07-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0025_auto_20200725_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpost',
            name='deleted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
