# Generated by Django 3.0.7 on 2020-09-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0027_iguserfollowedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_de',
            field=models.TextField(null=True,
                                   verbose_name='Project description'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_de',
            field=models.CharField(max_length=255,
                                   null=True,
                                   verbose_name='Project name'),
        ),
    ]
