# Generated by Django 3.0.11 on 2021-04-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0032_project_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igpost',
            name='ig_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='ig_observer.IgUser'),
        ),
    ]
