# Generated by Django 3.0.11 on 2021-04-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_observer', '0033_auto_20210413_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igimage',
            name='image_url',
            field=models.URLField(max_length=510),
        ),
    ]
